# This docker-compose file is used to set up the dshackle service with the necessary configurations and mappings.
version: "3"
services:
  dshackle:
    container_name: dshackle
    image: drpcorg/dshackle:latest
    volumes:
      - "./config/dshackle.yaml:/etc/dshackle/dshackle.yaml"
      - "./ssl_certs:/path_to_ssl_certs"
      - "./keys:/path_to_keys"
    ports:
      - "12448:12448"
