# This docker-compose.yaml file defines a service named `dshackle` that uses the `drpcorg/dshackle:latest` image.
# It also maps volumes and ports as specified below.

version: "3"
services:
  dshackle:
    container_name: dshackle
    image: drpcorg/dshackle:latest
    volumes:
      - "./dshackle.yaml:/etc/dshackle/dshackle.yaml"
      - "./ssl_certs:/path_to_ssl_certs"
      - "./keys:/path_to_keys"
    ports:
      - "12448:12448"
